<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509080525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_entry DROP CONSTRAINT fk_a8bfe98dba364942');
        $this->addSql('ALTER TABLE purchase_entry DROP CONSTRAINT fk_ffea1e5aba364942');
        $this->addSql('DROP INDEX uniq_a8bfe98dba364942');
        $this->addSql('DROP INDEX uniq_ffea1e5aba364942');
        $this->addSql('ALTER TABLE entry DROP CONSTRAINT fk_2b219d702d8503b6');
        $this->addSql('DROP TABLE entry');
        $this->addSql("ALTER TABLE category ADD status VARCHAR(255) DEFAULT 'active' NOT NULL");
        $this->addSql('ALTER TABLE category ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE category ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE category ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_64C19C1B03A8386 ON category (created_by_id)');
        $this->addSql('CREATE INDEX IDX_64C19C1896DBBDE ON category (updated_by_id)');
        $this->addSql("ALTER TABLE order_entry ADD quantity NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE order_entry ADD shipped_quantity NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE order_entry ADD returned_quantity NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE order_entry ADD canceled_quantity NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE order_entry ADD unit_price NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD unit_price_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE order_entry ADD discount_amount NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE order_entry ADD discount_amount_base NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE order_entry ADD total_price NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD total_price_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD product_name_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD product_code_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD unit_code_snapshot VARCHAR(50) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE order_entry ADD unit_name_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql('ALTER TABLE order_entry ADD warehouse_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE order_entry RENAME COLUMN entry_id TO product_id');
        $this->addSql('ALTER TABLE order_entry ADD CONSTRAINT FK_A8BFE98D4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_entry ADD CONSTRAINT FK_A8BFE98D5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
        $this->addSql('CREATE INDEX IDX_A8BFE98D4584665A ON order_entry (product_id)');
        $this->addSql('CREATE INDEX IDX_A8BFE98D5080ECDE ON order_entry (warehouse_id)');
        $this->addSql("ALTER TABLE orders ADD number VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE orders ADD exchange_rate_to_base NUMERIC(18, 8) DEFAULT '1.00000000' NOT NULL");
        $this->addSql('ALTER TABLE orders ADD customer_name_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD customer_phone_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD customer_email_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD delivery_address TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD comment TEXT DEFAULT NULL');
        $this->addSql("ALTER TABLE orders ADD total_amount NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE orders ADD total_amount_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE orders ADD discount_amount NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD discount_amount_base NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE orders ADD paid_amount_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE orders ADD payment_status VARCHAR(255) DEFAULT 'unpaid' NOT NULL");
        $this->addSql('ALTER TABLE orders ADD paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD canceled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE orders ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql("ALTER TABLE orders ADD currency_id VARCHAR(3) DEFAULT 'UAH' NOT NULL");
        $this->addSql('ALTER TABLE orders ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD canceled_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE38248176 FOREIGN KEY (currency_id) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEEB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE1418957 FOREIGN KEY (canceled_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE38248176 ON orders (currency_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEEB03A8386 ON orders (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE896DBBDE ON orders (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE1418957 ON orders (canceled_by_id)');
        $this->addSql("ALTER TABLE purchase ADD number VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE purchase ADD exchange_rate_to_base NUMERIC(18, 8) DEFAULT '1.00000000' NOT NULL");
        $this->addSql('ALTER TABLE purchase ADD supplier_name_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD supplier_phone_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD supplier_email_snapshot VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD invoice_number VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD document_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD comment TEXT DEFAULT NULL');
        $this->addSql("ALTER TABLE purchase ADD total_amount NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE purchase ADD total_amount_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE purchase ADD delivery_cost NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD delivery_cost_base NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD canceled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql("ALTER TABLE purchase ADD paid_amount_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE purchase ADD payment_status VARCHAR(255) DEFAULT 'unpaid' NOT NULL");
        $this->addSql('ALTER TABLE purchase ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE purchase ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql("ALTER TABLE purchase ADD currency_id VARCHAR(3) DEFAULT 'UAH' NOT NULL");
        $this->addSql('ALTER TABLE purchase ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD canceled_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B38248176 FOREIGN KEY (currency_id) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13BB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B1418957 FOREIGN KEY (canceled_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_6117D13B38248176 ON purchase (currency_id)');
        $this->addSql('CREATE INDEX IDX_6117D13BB03A8386 ON purchase (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B896DBBDE ON purchase (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_6117D13B1418957 ON purchase (canceled_by_id)');
        $this->addSql("ALTER TABLE purchase_entry ADD quantity NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE purchase_entry ADD received_quantity NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase_entry ADD returned_quantity NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE purchase_entry ADD unit_cost NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE purchase_entry ADD unit_cost_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE purchase_entry ADD delivery_cost NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase_entry ADD delivery_cost_base NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE purchase_entry ADD total_cost NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE purchase_entry ADD total_cost_base NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE purchase_entry ADD sale_price NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase_entry ADD sale_price_base NUMERIC(14, 4) DEFAULT NULL');
        $this->addSql("ALTER TABLE purchase_entry ADD product_name_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE purchase_entry ADD product_code_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE purchase_entry ADD unit_code_snapshot VARCHAR(50) DEFAULT '' NOT NULL");
        $this->addSql("ALTER TABLE purchase_entry ADD unit_name_snapshot VARCHAR(255) DEFAULT '' NOT NULL");
        $this->addSql('ALTER TABLE purchase_entry ADD warehouse_id INT NOT NULL');
        $this->addSql('ALTER TABLE purchase_entry RENAME COLUMN entry_id TO product_id');
        $this->addSql('ALTER TABLE purchase_entry ADD CONSTRAINT FK_FFEA1E5A4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE purchase_entry ADD CONSTRAINT FK_FFEA1E5A5080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_FFEA1E5A4584665A ON purchase_entry (product_id)');
        $this->addSql('CREATE INDEX IDX_FFEA1E5A5080ECDE ON purchase_entry (warehouse_id)');
        $this->addSql("ALTER TABLE warehouse ADD status VARCHAR(255) DEFAULT 'active' NOT NULL");
        $this->addSql('ALTER TABLE warehouse ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE warehouse ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE warehouse ADD deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse ADD created_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse ADD updated_by_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFCB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('CREATE INDEX IDX_ECB38BFCB03A8386 ON warehouse (created_by_id)');
        $this->addSql('CREATE INDEX IDX_ECB38BFC896DBBDE ON warehouse (updated_by_id)');
        $this->addSql("ALTER TABLE warehouse_stock ADD reserved_quantity NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE warehouse_stock ADD average_cost NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql("ALTER TABLE warehouse_stock ADD quantity_on_hand NUMERIC(14, 4) DEFAULT '0.0000' NOT NULL");
        $this->addSql('ALTER TABLE warehouse_stock ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('UPDATE warehouse_stock SET quantity_on_hand = count, reserved_quantity = reserve_count, average_cost = average_cost_price');
        $this->addSql('ALTER TABLE warehouse_stock DROP average_cost_price');
        $this->addSql('ALTER TABLE warehouse_stock DROP count');
        $this->addSql('ALTER TABLE warehouse_stock DROP reserve_count');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP CONSTRAINT fk_9622af505080ecde');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP CONSTRAINT fk_9622af504584665a');
        $this->addSql('DROP INDEX idx_9622af504584665a');
        $this->addSql('DROP INDEX idx_9622af505080ecde');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP product_id');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP warehouse_id');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER initial_quantity TYPE NUMERIC(14, 4)');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER remaining_quantity TYPE NUMERIC(14, 4)');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER sale_price DROP NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER purchase_entry_id DROP NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch RENAME COLUMN purchase_price TO unit_cost');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cost NUMERIC(14, 4) NOT NULL, delivery_cost NUMERIC(10, 4) DEFAULT NULL, warehouse_stock_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_2b219d702d8503b6 ON entry (warehouse_stock_id)');
        $this->addSql('ALTER TABLE entry ADD CONSTRAINT fk_2b219d702d8503b6 FOREIGN KEY (warehouse_stock_id) REFERENCES warehouse_stock (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1B03A8386');
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C1896DBBDE');
        $this->addSql('DROP INDEX IDX_64C19C1B03A8386');
        $this->addSql('DROP INDEX IDX_64C19C1896DBBDE');
        $this->addSql('ALTER TABLE category DROP status');
        $this->addSql('ALTER TABLE category DROP created_at');
        $this->addSql('ALTER TABLE category DROP updated_at');
        $this->addSql('ALTER TABLE category DROP deleted_at');
        $this->addSql('ALTER TABLE category DROP created_by_id');
        $this->addSql('ALTER TABLE category DROP updated_by_id');
        $this->addSql('ALTER TABLE order_entry DROP CONSTRAINT FK_A8BFE98D4584665A');
        $this->addSql('ALTER TABLE order_entry DROP CONSTRAINT FK_A8BFE98D5080ECDE');
        $this->addSql('DROP INDEX IDX_A8BFE98D4584665A');
        $this->addSql('DROP INDEX IDX_A8BFE98D5080ECDE');
        $this->addSql('ALTER TABLE order_entry DROP quantity');
        $this->addSql('ALTER TABLE order_entry DROP shipped_quantity');
        $this->addSql('ALTER TABLE order_entry DROP returned_quantity');
        $this->addSql('ALTER TABLE order_entry DROP canceled_quantity');
        $this->addSql('ALTER TABLE order_entry DROP unit_price');
        $this->addSql('ALTER TABLE order_entry DROP unit_price_base');
        $this->addSql('ALTER TABLE order_entry DROP discount_amount');
        $this->addSql('ALTER TABLE order_entry DROP discount_amount_base');
        $this->addSql('ALTER TABLE order_entry DROP total_price');
        $this->addSql('ALTER TABLE order_entry DROP total_price_base');
        $this->addSql('ALTER TABLE order_entry DROP product_name_snapshot');
        $this->addSql('ALTER TABLE order_entry DROP product_code_snapshot');
        $this->addSql('ALTER TABLE order_entry DROP unit_code_snapshot');
        $this->addSql('ALTER TABLE order_entry DROP unit_name_snapshot');
        $this->addSql('ALTER TABLE order_entry DROP warehouse_id');
        $this->addSql('ALTER TABLE order_entry RENAME COLUMN product_id TO entry_id');
        $this->addSql('ALTER TABLE order_entry ADD CONSTRAINT fk_a8bfe98dba364942 FOREIGN KEY (entry_id) REFERENCES entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_a8bfe98dba364942 ON order_entry (entry_id)');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE38248176');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEEB03A8386');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE896DBBDE');
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE1418957');
        $this->addSql('DROP INDEX IDX_E52FFDEE38248176');
        $this->addSql('DROP INDEX IDX_E52FFDEEB03A8386');
        $this->addSql('DROP INDEX IDX_E52FFDEE896DBBDE');
        $this->addSql('DROP INDEX IDX_E52FFDEE1418957');
        $this->addSql('ALTER TABLE orders DROP number');
        $this->addSql('ALTER TABLE orders DROP exchange_rate_to_base');
        $this->addSql('ALTER TABLE orders DROP customer_name_snapshot');
        $this->addSql('ALTER TABLE orders DROP customer_phone_snapshot');
        $this->addSql('ALTER TABLE orders DROP customer_email_snapshot');
        $this->addSql('ALTER TABLE orders DROP delivery_address');
        $this->addSql('ALTER TABLE orders DROP comment');
        $this->addSql('ALTER TABLE orders DROP total_amount');
        $this->addSql('ALTER TABLE orders DROP total_amount_base');
        $this->addSql('ALTER TABLE orders DROP discount_amount');
        $this->addSql('ALTER TABLE orders DROP discount_amount_base');
        $this->addSql('ALTER TABLE orders DROP paid_amount_base');
        $this->addSql('ALTER TABLE orders DROP payment_status');
        $this->addSql('ALTER TABLE orders DROP paid_at');
        $this->addSql('ALTER TABLE orders DROP canceled_at');
        $this->addSql('ALTER TABLE orders DROP created_at');
        $this->addSql('ALTER TABLE orders DROP updated_at');
        $this->addSql('ALTER TABLE orders DROP currency_id');
        $this->addSql('ALTER TABLE orders DROP created_by_id');
        $this->addSql('ALTER TABLE orders DROP updated_by_id');
        $this->addSql('ALTER TABLE orders DROP canceled_by_id');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B38248176');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13BB03A8386');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B896DBBDE');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B1418957');
        $this->addSql('DROP INDEX IDX_6117D13B38248176');
        $this->addSql('DROP INDEX IDX_6117D13BB03A8386');
        $this->addSql('DROP INDEX IDX_6117D13B896DBBDE');
        $this->addSql('DROP INDEX IDX_6117D13B1418957');
        $this->addSql('ALTER TABLE purchase DROP number');
        $this->addSql('ALTER TABLE purchase DROP exchange_rate_to_base');
        $this->addSql('ALTER TABLE purchase DROP supplier_name_snapshot');
        $this->addSql('ALTER TABLE purchase DROP supplier_phone_snapshot');
        $this->addSql('ALTER TABLE purchase DROP supplier_email_snapshot');
        $this->addSql('ALTER TABLE purchase DROP invoice_number');
        $this->addSql('ALTER TABLE purchase DROP document_date');
        $this->addSql('ALTER TABLE purchase DROP comment');
        $this->addSql('ALTER TABLE purchase DROP total_amount');
        $this->addSql('ALTER TABLE purchase DROP total_amount_base');
        $this->addSql('ALTER TABLE purchase DROP delivery_cost');
        $this->addSql('ALTER TABLE purchase DROP delivery_cost_base');
        $this->addSql('ALTER TABLE purchase DROP canceled_at');
        $this->addSql('ALTER TABLE purchase DROP paid_amount_base');
        $this->addSql('ALTER TABLE purchase DROP payment_status');
        $this->addSql('ALTER TABLE purchase DROP created_at');
        $this->addSql('ALTER TABLE purchase DROP updated_at');
        $this->addSql('ALTER TABLE purchase DROP currency_id');
        $this->addSql('ALTER TABLE purchase DROP created_by_id');
        $this->addSql('ALTER TABLE purchase DROP updated_by_id');
        $this->addSql('ALTER TABLE purchase DROP canceled_by_id');
        $this->addSql('ALTER TABLE purchase_entry DROP CONSTRAINT FK_FFEA1E5A4584665A');
        $this->addSql('ALTER TABLE purchase_entry DROP CONSTRAINT FK_FFEA1E5A5080ECDE');
        $this->addSql('DROP INDEX IDX_FFEA1E5A4584665A');
        $this->addSql('DROP INDEX IDX_FFEA1E5A5080ECDE');
        $this->addSql('ALTER TABLE purchase_entry ADD entry_id INT NOT NULL');
        $this->addSql('ALTER TABLE purchase_entry DROP quantity');
        $this->addSql('ALTER TABLE purchase_entry DROP received_quantity');
        $this->addSql('ALTER TABLE purchase_entry DROP returned_quantity');
        $this->addSql('ALTER TABLE purchase_entry DROP unit_cost');
        $this->addSql('ALTER TABLE purchase_entry DROP unit_cost_base');
        $this->addSql('ALTER TABLE purchase_entry DROP delivery_cost');
        $this->addSql('ALTER TABLE purchase_entry DROP delivery_cost_base');
        $this->addSql('ALTER TABLE purchase_entry DROP total_cost');
        $this->addSql('ALTER TABLE purchase_entry DROP total_cost_base');
        $this->addSql('ALTER TABLE purchase_entry DROP sale_price');
        $this->addSql('ALTER TABLE purchase_entry DROP sale_price_base');
        $this->addSql('ALTER TABLE purchase_entry DROP product_name_snapshot');
        $this->addSql('ALTER TABLE purchase_entry DROP product_code_snapshot');
        $this->addSql('ALTER TABLE purchase_entry DROP unit_code_snapshot');
        $this->addSql('ALTER TABLE purchase_entry DROP unit_name_snapshot');
        $this->addSql('ALTER TABLE purchase_entry DROP product_id');
        $this->addSql('ALTER TABLE purchase_entry DROP warehouse_id');
        $this->addSql('ALTER TABLE purchase_entry ADD CONSTRAINT fk_ffea1e5aba364942 FOREIGN KEY (entry_id) REFERENCES entry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE UNIQUE INDEX uniq_ffea1e5aba364942 ON purchase_entry (entry_id)');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFCB03A8386');
        $this->addSql('ALTER TABLE warehouse DROP CONSTRAINT FK_ECB38BFC896DBBDE');
        $this->addSql('DROP INDEX IDX_ECB38BFCB03A8386');
        $this->addSql('DROP INDEX IDX_ECB38BFC896DBBDE');
        $this->addSql('ALTER TABLE warehouse DROP status');
        $this->addSql('ALTER TABLE warehouse DROP created_at');
        $this->addSql('ALTER TABLE warehouse DROP updated_at');
        $this->addSql('ALTER TABLE warehouse DROP deleted_at');
        $this->addSql('ALTER TABLE warehouse DROP created_by_id');
        $this->addSql('ALTER TABLE warehouse DROP updated_by_id');
        $this->addSql('ALTER TABLE warehouse_stock ADD average_cost_price NUMERIC(14, 4) NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock ADD count INT NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock ADD reserve_count INT NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock DROP quantity_on_hand');
        $this->addSql('ALTER TABLE warehouse_stock DROP reserved_quantity');
        $this->addSql('ALTER TABLE warehouse_stock DROP average_cost');
        $this->addSql('ALTER TABLE warehouse_stock DROP created_at');
        $this->addSql('ALTER TABLE warehouse_stock DROP updated_at');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD product_id INT NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD warehouse_id INT NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP created_at');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER initial_quantity TYPE INT');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER remaining_quantity TYPE INT');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER sale_price SET NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch ALTER purchase_entry_id SET NOT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch RENAME COLUMN unit_cost TO purchase_price');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD CONSTRAINT fk_9622af505080ecde FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD CONSTRAINT fk_9622af504584665a FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_9622af504584665a ON warehouse_stock_batch (product_id)');
        $this->addSql('CREATE INDEX idx_9622af505080ecde ON warehouse_stock_batch (warehouse_id)');
    }
}
