<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260525130000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add append-only payment history for order and purchase timelines.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE payment_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_key VARCHAR(100) NOT NULL, document_type VARCHAR(32) NOT NULL, document_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, amount NUMERIC(14, 4) NOT NULL, amount_base NUMERIC(14, 4) NOT NULL, currency_code VARCHAR(3) NOT NULL, direction VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, external_reference VARCHAR(255) DEFAULT NULL, payload JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_name_snapshot VARCHAR(255) DEFAULT NULL, store_id INT NOT NULL, order_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, payment_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_4A99E7BEB092A811 ON payment_history (store_id)');
		$this->addSql('CREATE INDEX IDX_4A99E7BE8D9F6D38 ON payment_history (order_id)');
		$this->addSql('CREATE INDEX IDX_4A99E7BE558FBEB9 ON payment_history (purchase_id)');
		$this->addSql('CREATE INDEX IDX_4A99E7BE4C3A3BB ON payment_history (payment_id)');
		$this->addSql('CREATE INDEX IDX_4A99E7BE10DAF24A ON payment_history (actor_id)');
		$this->addSql('CREATE INDEX idx_payment_history_store_document_occurred_at ON payment_history (store_id, document_type, document_id, occurred_at)');
		$this->addSql('CREATE INDEX idx_payment_history_store_occurred_at ON payment_history (store_id, occurred_at)');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT FK_4A99E7BEB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT FK_4A99E7BE8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT FK_4A99E7BE558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT FK_4A99E7BE4C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT FK_4A99E7BE10DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE payment_history ADD CONSTRAINT chk_payment_history_document CHECK (((order_id IS NOT NULL)::integer + (purchase_id IS NOT NULL)::integer) = 1)');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT chk_payment_history_document');
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT FK_4A99E7BEB092A811');
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT FK_4A99E7BE8D9F6D38');
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT FK_4A99E7BE558FBEB9');
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT FK_4A99E7BE4C3A3BB');
		$this->addSql('ALTER TABLE payment_history DROP CONSTRAINT FK_4A99E7BE10DAF24A');
		$this->addSql('DROP TABLE payment_history');
	}
}
