<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260520172047 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add inventory documents, reasons, lines, movements and document progress links.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE inventory_document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, number VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, document_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, exchange_rate_to_base NUMERIC(18, 8) DEFAULT NULL, total_amount NUMERIC(14, 4) DEFAULT NULL, total_amount_base NUMERIC(14, 4) DEFAULT NULL, posted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, canceled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, currency_code VARCHAR(3) DEFAULT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, posted_by_id INT DEFAULT NULL, canceled_by_id INT DEFAULT NULL, reversed_document_id INT DEFAULT NULL, order_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, reason_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C2330E7FDA273EC ON inventory_document (currency_code)');
        $this->addSql('CREATE INDEX IDX_6C2330E7B092A811 ON inventory_document (store_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E7B03A8386 ON inventory_document (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E7896DBBDE ON inventory_document (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E75A6D2235 ON inventory_document (posted_by_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E71418957 ON inventory_document (canceled_by_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E770044975 ON inventory_document (reversed_document_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E78D9F6D38 ON inventory_document (order_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E7558FBEB9 ON inventory_document (purchase_id)');
        $this->addSql('CREATE INDEX IDX_6C2330E759BB1592 ON inventory_document (reason_id)');
        $this->addSql('CREATE INDEX idx_inventory_document_store_status ON inventory_document (store_id, status)');
        $this->addSql('CREATE INDEX idx_inventory_document_store_type ON inventory_document (store_id, type)');
        $this->addSql('CREATE INDEX idx_inventory_document_document_date ON inventory_document (document_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_document_store_number ON inventory_document (store_id, number)');
        $this->addSql('CREATE TABLE inventory_document_line (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(14, 4) NOT NULL, unit_price NUMERIC(14, 4) DEFAULT NULL, unit_price_base NUMERIC(14, 4) DEFAULT NULL, total_price NUMERIC(14, 4) DEFAULT NULL, total_price_base NUMERIC(14, 4) DEFAULT NULL, direction VARCHAR(255) NOT NULL, inventory_document_id INT NOT NULL, product_id INT NOT NULL, warehouse_id INT NOT NULL, warehouse_stock_id INT DEFAULT NULL, order_entry_id INT DEFAULT NULL, purchase_entry_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15ADFB914584665A ON inventory_document_line (product_id)');
        $this->addSql('CREATE INDEX IDX_15ADFB915080ECDE ON inventory_document_line (warehouse_id)');
        $this->addSql('CREATE INDEX IDX_15ADFB912D8503B6 ON inventory_document_line (warehouse_stock_id)');
        $this->addSql('CREATE INDEX IDX_15ADFB915BCEABF3 ON inventory_document_line (order_entry_id)');
        $this->addSql('CREATE INDEX IDX_15ADFB9193F45A10 ON inventory_document_line (purchase_entry_id)');
        $this->addSql('CREATE INDEX idx_inventory_document_line_document ON inventory_document_line (inventory_document_id)');
        $this->addSql('CREATE INDEX idx_inventory_document_line_product_warehouse ON inventory_document_line (product_id, warehouse_id)');
        $this->addSql('CREATE TABLE inventory_reason (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3B6414A7B092A811 ON inventory_reason (store_id)');
        $this->addSql('CREATE INDEX IDX_3B6414A7B03A8386 ON inventory_reason (created_by_id)');
        $this->addSql('CREATE INDEX IDX_3B6414A7896DBBDE ON inventory_reason (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_inventory_reason_store_type_name ON inventory_reason (store_id, type, name)');
        $this->addSql('CREATE TABLE stock_movement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity_change NUMERIC(14, 4) NOT NULL, unit_cost NUMERIC(14, 4) NOT NULL, balance_after NUMERIC(14, 4) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, inventory_document_line_id INT NOT NULL, warehouse_stock_id INT NOT NULL, warehouse_stock_batch_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB1BC1B52D8503B6 ON stock_movement (warehouse_stock_id)');
        $this->addSql('CREATE INDEX idx_stock_movement_warehouse_stock_created_at ON stock_movement (warehouse_stock_id, created_at)');
        $this->addSql('CREATE INDEX idx_stock_movement_line ON stock_movement (inventory_document_line_id)');
        $this->addSql('CREATE INDEX idx_stock_movement_batch ON stock_movement (warehouse_stock_batch_id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E7FDA273EC FOREIGN KEY (currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E7B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E7B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E75A6D2235 FOREIGN KEY (posted_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E71418957 FOREIGN KEY (canceled_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E770044975 FOREIGN KEY (reversed_document_id) REFERENCES inventory_document (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E78D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E7558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E759BB1592 FOREIGN KEY (reason_id) REFERENCES inventory_reason (id)');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB91B7CD44F8 FOREIGN KEY (inventory_document_id) REFERENCES inventory_document (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB914584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB915080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB912D8503B6 FOREIGN KEY (warehouse_stock_id) REFERENCES warehouse_stock (id)');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB915BCEABF3 FOREIGN KEY (order_entry_id) REFERENCES order_entry (id)');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT FK_15ADFB9193F45A10 FOREIGN KEY (purchase_entry_id) REFERENCES purchase_entry (id)');
        $this->addSql('ALTER TABLE inventory_reason ADD CONSTRAINT FK_3B6414A7B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inventory_reason ADD CONSTRAINT FK_3B6414A7B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE inventory_reason ADD CONSTRAINT FK_3B6414A7896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B5C5BFF0C1 FOREIGN KEY (inventory_document_line_id) REFERENCES inventory_document_line (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B52D8503B6 FOREIGN KEY (warehouse_stock_id) REFERENCES warehouse_stock (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT FK_BB1BC1B5F6020AD4 FOREIGN KEY (warehouse_stock_batch_id) REFERENCES warehouse_stock_batch (id)');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD created_by_movement_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE warehouse_stock_batch ADD CONSTRAINT FK_9622AF5082A7CBC7 FOREIGN KEY (created_by_movement_id) REFERENCES stock_movement (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9622AF5082A7CBC7 ON warehouse_stock_batch (created_by_movement_id)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_exchange_rate_positive CHECK (exchange_rate_to_base IS NULL OR exchange_rate_to_base > 0)');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_nonnegative_totals CHECK ((total_amount IS NULL OR total_amount >= 0) AND (total_amount_base IS NULL OR total_amount_base >= 0))');
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_single_business_document CHECK (((order_id IS NOT NULL)::int + (purchase_id IS NOT NULL)::int) <= 1)');
        $this->addSql("ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_posted_audit CHECK (status <> 'posted' OR posted_at IS NOT NULL)");
        $this->addSql("ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_canceled_audit CHECK (status <> 'canceled' OR canceled_at IS NOT NULL)");
        $this->addSql("ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_reversal_target CHECK ((type = 'reversal' AND reversed_document_id IS NOT NULL) OR (type <> 'reversal' AND reversed_document_id IS NULL))");
        $this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_not_self_reversal CHECK (reversed_document_id IS NULL OR reversed_document_id <> id)');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT chk_inventory_document_line_quantity_positive CHECK (quantity > 0)');
        $this->addSql('ALTER TABLE inventory_document_line ADD CONSTRAINT chk_inventory_document_line_nonnegative_prices CHECK ((unit_price IS NULL OR unit_price >= 0) AND (unit_price_base IS NULL OR unit_price_base >= 0) AND (total_price IS NULL OR total_price >= 0) AND (total_price_base IS NULL OR total_price_base >= 0))');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT chk_stock_movement_quantity_change_nonzero CHECK (quantity_change <> 0)');
        $this->addSql('ALTER TABLE stock_movement ADD CONSTRAINT chk_stock_movement_unit_cost_nonnegative CHECK (unit_cost >= 0)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E7FDA273EC');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E7B092A811');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E7B03A8386');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E7896DBBDE');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E75A6D2235');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E71418957');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E770044975');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E78D9F6D38');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E7558FBEB9');
        $this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E759BB1592');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB91B7CD44F8');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB914584665A');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB915080ECDE');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB912D8503B6');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB915BCEABF3');
        $this->addSql('ALTER TABLE inventory_document_line DROP CONSTRAINT FK_15ADFB9193F45A10');
        $this->addSql('ALTER TABLE inventory_reason DROP CONSTRAINT FK_3B6414A7B092A811');
        $this->addSql('ALTER TABLE inventory_reason DROP CONSTRAINT FK_3B6414A7B03A8386');
        $this->addSql('ALTER TABLE inventory_reason DROP CONSTRAINT FK_3B6414A7896DBBDE');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B5C5BFF0C1');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B52D8503B6');
        $this->addSql('ALTER TABLE stock_movement DROP CONSTRAINT FK_BB1BC1B5F6020AD4');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP CONSTRAINT FK_9622AF5082A7CBC7');
        $this->addSql('DROP TABLE inventory_document');
        $this->addSql('DROP TABLE inventory_document_line');
        $this->addSql('DROP TABLE inventory_reason');
        $this->addSql('DROP TABLE stock_movement');
        $this->addSql('DROP INDEX UNIQ_9622AF5082A7CBC7');
        $this->addSql('ALTER TABLE warehouse_stock_batch DROP created_by_movement_id');
    }
}
