<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602203127 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add product_relation table for bidirectional related products (table -> chairs, legs, hardware).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE product_relation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, sort_order SMALLINT DEFAULT 0 NOT NULL, product_id INT NOT NULL, related_product_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A9392DDE4584665A ON product_relation (product_id)');
        $this->addSql('CREATE INDEX IDX_A9392DDECF496EEA ON product_relation (related_product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_relation ON product_relation (product_id, related_product_id)');
        $this->addSql('ALTER TABLE product_relation ADD CONSTRAINT FK_A9392DDE4584665A FOREIGN KEY (product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_relation ADD CONSTRAINT FK_A9392DDECF496EEA FOREIGN KEY (related_product_id) REFERENCES product (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_relation DROP CONSTRAINT FK_A9392DDE4584665A');
        $this->addSql('ALTER TABLE product_relation DROP CONSTRAINT FK_A9392DDECF496EEA');
        $this->addSql('DROP TABLE product_relation');
    }
}
