<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260520190000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add production recipes, production orders and inventory document production links.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE production_recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id INT NOT NULL, product_id INT NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_9FD5553AB092A811 ON production_recipe (store_id)');
		$this->addSql('CREATE INDEX IDX_9FD5553A4584665A ON production_recipe (product_id)');
		$this->addSql('CREATE INDEX idx_production_recipe_store_status ON production_recipe (store_id, status)');
		$this->addSql('CREATE UNIQUE INDEX uniq_production_recipe_store_product_default ON production_recipe (store_id, product_id) WHERE is_default = true');
		$this->addSql('CREATE TABLE production_recipe_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantity NUMERIC(14, 4) NOT NULL, waste_percent NUMERIC(5, 2) DEFAULT NULL, recipe_id INT NOT NULL, material_id INT NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_B5D8C39959D8A214 ON production_recipe_item (recipe_id)');
		$this->addSql('CREATE INDEX idx_production_recipe_item_material ON production_recipe_item (material_id)');
		$this->addSql('CREATE TABLE production_order (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, planned_quantity NUMERIC(14, 4) NOT NULL, completed_quantity NUMERIC(14, 4) DEFAULT NULL, planned_start_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, planned_end_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, canceled_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, started_by_id INT DEFAULT NULL, completed_by_id INT DEFAULT NULL, canceled_by_id INT DEFAULT NULL, product_id INT NOT NULL, warehouse_id INT DEFAULT NULL, recipe_id INT DEFAULT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_6B4E96E1B092A811 ON production_order (store_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E1B03A8386 ON production_order (created_by_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E1896DBBDE ON production_order (updated_by_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E1B3BA5A5A ON production_order (started_by_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E1FA67B0F2 ON production_order (completed_by_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E11418957 ON production_order (canceled_by_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E14584665A ON production_order (product_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E15080ECDE ON production_order (warehouse_id)');
		$this->addSql('CREATE INDEX IDX_6B4E96E159D8A214 ON production_order (recipe_id)');
		$this->addSql('CREATE INDEX idx_production_order_store_status ON production_order (store_id, status)');
		$this->addSql('CREATE INDEX idx_production_order_planned_start ON production_order (planned_start_at)');
		$this->addSql('CREATE TABLE production_order_material (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, planned_quantity NUMERIC(14, 4) NOT NULL, waste_percent NUMERIC(5, 2) DEFAULT NULL, comment TEXT DEFAULT NULL, production_order_id INT NOT NULL, material_id INT NOT NULL, recipe_item_id INT DEFAULT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_6B7C50EBFADE5CB7 ON production_order_material (production_order_id)');
		$this->addSql('CREATE INDEX idx_production_order_material_product ON production_order_material (material_id)');
		$this->addSql('CREATE INDEX IDX_6B7C50EB48EC5212 ON production_order_material (recipe_item_id)');
		$this->addSql('ALTER TABLE production_recipe ADD CONSTRAINT FK_9FD5553AB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_recipe ADD CONSTRAINT FK_9FD5553A4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_recipe_item ADD CONSTRAINT FK_B5D8C39959D8A214 FOREIGN KEY (recipe_id) REFERENCES production_recipe (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_recipe_item ADD CONSTRAINT FK_B5D8C3997F5A1AA FOREIGN KEY (material_id) REFERENCES product (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E1B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E1B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E1896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E1B3BA5A5A FOREIGN KEY (started_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E1FA67B0F2 FOREIGN KEY (completed_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E11418957 FOREIGN KEY (canceled_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E14584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E15080ECDE FOREIGN KEY (warehouse_id) REFERENCES warehouse (id)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT FK_6B4E96E159D8A214 FOREIGN KEY (recipe_id) REFERENCES production_recipe (id)');
		$this->addSql('ALTER TABLE production_order_material ADD CONSTRAINT FK_6B7C50EBFADE5CB7 FOREIGN KEY (production_order_id) REFERENCES production_order (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_order_material ADD CONSTRAINT FK_6B7C50EB7F5A1AA FOREIGN KEY (material_id) REFERENCES product (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE production_order_material ADD CONSTRAINT FK_6B7C50EB48EC5212 FOREIGN KEY (recipe_item_id) REFERENCES production_recipe_item (id)');
		$this->addSql('ALTER TABLE inventory_document ADD production_order_id INT DEFAULT NULL');
		$this->addSql('CREATE INDEX IDX_6C2330E1FADE5CB7 ON inventory_document (production_order_id)');
		$this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT FK_6C2330E1FADE5CB7 FOREIGN KEY (production_order_id) REFERENCES production_order (id)');
		$this->addSql('ALTER TABLE production_recipe_item ADD CONSTRAINT chk_production_recipe_item_quantity_positive CHECK (quantity > 0)');
		$this->addSql('ALTER TABLE production_recipe_item ADD CONSTRAINT chk_production_recipe_item_waste_nonnegative CHECK (waste_percent IS NULL OR waste_percent >= 0)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT chk_production_order_planned_quantity_positive CHECK (planned_quantity > 0)');
		$this->addSql('ALTER TABLE production_order ADD CONSTRAINT chk_production_order_completed_quantity_nonnegative CHECK (completed_quantity IS NULL OR completed_quantity >= 0)');
		$this->addSql("ALTER TABLE production_order ADD CONSTRAINT chk_production_order_started_audit CHECK (status <> 'in_progress' OR started_at IS NOT NULL)");
		$this->addSql("ALTER TABLE production_order ADD CONSTRAINT chk_production_order_completed_audit CHECK (status <> 'completed' OR completed_at IS NOT NULL)");
		$this->addSql("ALTER TABLE production_order ADD CONSTRAINT chk_production_order_canceled_audit CHECK (status <> 'canceled' OR canceled_at IS NOT NULL)");
		$this->addSql('ALTER TABLE production_order_material ADD CONSTRAINT chk_production_order_material_quantity_positive CHECK (planned_quantity > 0)');
		$this->addSql('ALTER TABLE production_order_material ADD CONSTRAINT chk_production_order_material_waste_nonnegative CHECK (waste_percent IS NULL OR waste_percent >= 0)');
		$this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT chk_inventory_document_single_business_document');
		$this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_single_business_document CHECK (((order_id IS NOT NULL)::int + (purchase_id IS NOT NULL)::int + (production_order_id IS NOT NULL)::int) <= 1)');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT chk_inventory_document_single_business_document');
		$this->addSql('ALTER TABLE inventory_document ADD CONSTRAINT chk_inventory_document_single_business_document CHECK (((order_id IS NOT NULL)::int + (purchase_id IS NOT NULL)::int) <= 1)');
		$this->addSql('ALTER TABLE inventory_document DROP CONSTRAINT FK_6C2330E1FADE5CB7');
		$this->addSql('DROP INDEX IDX_6C2330E1FADE5CB7');
		$this->addSql('ALTER TABLE inventory_document DROP production_order_id');
		$this->addSql('ALTER TABLE production_order_material DROP CONSTRAINT FK_6B7C50EBFADE5CB7');
		$this->addSql('ALTER TABLE production_order_material DROP CONSTRAINT FK_6B7C50EB7F5A1AA');
		$this->addSql('ALTER TABLE production_order_material DROP CONSTRAINT FK_6B7C50EB48EC5212');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E1B092A811');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E1B03A8386');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E1896DBBDE');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E1B3BA5A5A');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E1FA67B0F2');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E11418957');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E14584665A');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E15080ECDE');
		$this->addSql('ALTER TABLE production_order DROP CONSTRAINT FK_6B4E96E159D8A214');
		$this->addSql('ALTER TABLE production_recipe_item DROP CONSTRAINT FK_B5D8C39959D8A214');
		$this->addSql('ALTER TABLE production_recipe_item DROP CONSTRAINT FK_B5D8C3997F5A1AA');
		$this->addSql('ALTER TABLE production_recipe DROP CONSTRAINT FK_9FD5553AB092A811');
		$this->addSql('ALTER TABLE production_recipe DROP CONSTRAINT FK_9FD5553A4584665A');
		$this->addSql('DROP TABLE production_order_material');
		$this->addSql('DROP TABLE production_order');
		$this->addSql('DROP TABLE production_recipe_item');
		$this->addSql('DROP TABLE production_recipe');
	}
}
