<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510074226 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE customer (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_81398E09B092A811 ON customer (store_id)');
        $this->addSql('CREATE INDEX IDX_81398E09B03A8386 ON customer (created_by_id)');
        $this->addSql('CREATE INDEX IDX_81398E09896DBBDE ON customer (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_store_email ON customer (store_id, email) WHERE (email IS NOT NULL AND deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_customer_store_phone ON customer (store_id, phone) WHERE (phone IS NOT NULL AND deleted_at IS NULL)');
        $this->addSql('CREATE TABLE supplier (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, phone VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9B2A6C7EB092A811 ON supplier (store_id)');
        $this->addSql('CREATE INDEX IDX_9B2A6C7EB03A8386 ON supplier (created_by_id)');
        $this->addSql('CREATE INDEX IDX_9B2A6C7E896DBBDE ON supplier (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_supplier_store_email ON supplier (store_id, email) WHERE (email IS NOT NULL AND deleted_at IS NULL)');
        $this->addSql('CREATE UNIQUE INDEX uniq_supplier_store_phone ON supplier (store_id, phone) WHERE (phone IS NOT NULL AND deleted_at IS NULL)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7EB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7EB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE supplier ADD CONSTRAINT FK_9B2A6C7E896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE orders ADD customer_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_E52FFDEE9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id)');
        $this->addSql('CREATE INDEX IDX_E52FFDEE9395C3F3 ON orders (customer_id)');
        $this->addSql('ALTER TABLE purchase ADD supplier_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE purchase ADD CONSTRAINT FK_6117D13B2ADD6D8C FOREIGN KEY (supplier_id) REFERENCES supplier (id)');
        $this->addSql('CREATE INDEX IDX_6117D13B2ADD6D8C ON purchase (supplier_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE orders DROP CONSTRAINT FK_E52FFDEE9395C3F3');
        $this->addSql('DROP INDEX IDX_E52FFDEE9395C3F3');
        $this->addSql('ALTER TABLE orders DROP customer_id');
        $this->addSql('ALTER TABLE purchase DROP CONSTRAINT FK_6117D13B2ADD6D8C');
        $this->addSql('DROP INDEX IDX_6117D13B2ADD6D8C');
        $this->addSql('ALTER TABLE purchase DROP supplier_id');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09B092A811');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09B03A8386');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09896DBBDE');
        $this->addSql('ALTER TABLE supplier DROP CONSTRAINT FK_9B2A6C7EB092A811');
        $this->addSql('ALTER TABLE supplier DROP CONSTRAINT FK_9B2A6C7EB03A8386');
        $this->addSql('ALTER TABLE supplier DROP CONSTRAINT FK_9B2A6C7E896DBBDE');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE supplier');
    }
}
