<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260516090000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add order comments and append-only order history.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE order_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, author_id INT NOT NULL, body TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
		$this->addSql('CREATE INDEX IDX_53B049768D9F6D38 ON order_comment (order_id)');
		$this->addSql('CREATE INDEX IDX_53B04976F675F31B ON order_comment (author_id)');
		$this->addSql('CREATE INDEX idx_order_comment_order_created_at ON order_comment (order_id, created_at)');
		$this->addSql('CREATE INDEX idx_order_comment_author_created_at ON order_comment (author_id, created_at)');
		$this->addSql('CREATE TABLE order_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id INT NOT NULL, actor_id INT DEFAULT NULL, event_key VARCHAR(100) NOT NULL, source VARCHAR(32) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, changes JSON DEFAULT NULL, payload JSON DEFAULT NULL, related_entity_type VARCHAR(100) DEFAULT NULL, related_entity_id INT DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_name_snapshot VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
		$this->addSql('CREATE INDEX IDX_5A2713518D9F6D38 ON order_history (order_id)');
		$this->addSql('CREATE INDEX IDX_5A27135110DAF24A ON order_history (actor_id)');
		$this->addSql('CREATE INDEX idx_order_history_order_occurred_at ON order_history (order_id, occurred_at)');
		$this->addSql('CREATE INDEX idx_order_history_order_event_occurred_at ON order_history (order_id, event_key, occurred_at)');
		$this->addSql('CREATE INDEX idx_order_history_actor_occurred_at ON order_history (actor_id, occurred_at)');
		$this->addSql('CREATE INDEX idx_order_history_source_occurred_at ON order_history (source, occurred_at)');
		$this->addSql('ALTER TABLE order_comment ADD CONSTRAINT FK_53B049768D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE order_comment ADD CONSTRAINT FK_53B04976F675F31B FOREIGN KEY (author_id) REFERENCES users (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE order_history ADD CONSTRAINT FK_5A2713518D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE order_history ADD CONSTRAINT FK_5A27135110DAF24A FOREIGN KEY (actor_id) REFERENCES users (id) NOT DEFERRABLE');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE order_comment DROP CONSTRAINT FK_53B049768D9F6D38');
		$this->addSql('ALTER TABLE order_comment DROP CONSTRAINT FK_53B04976F675F31B');
		$this->addSql('ALTER TABLE order_history DROP CONSTRAINT FK_5A2713518D9F6D38');
		$this->addSql('ALTER TABLE order_history DROP CONSTRAINT FK_5A27135110DAF24A');
		$this->addSql('DROP TABLE order_comment');
		$this->addSql('DROP TABLE order_history');
	}
}
