<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260518110000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add payment records and purchase paid_at cache field.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('ALTER TABLE purchase ADD paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
		$this->addSql('CREATE TABLE payment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, currency_code VARCHAR(3) NOT NULL, store_id INT NOT NULL, order_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, direction VARCHAR(255) NOT NULL, type VARCHAR(255) NOT NULL, amount NUMERIC(14, 4) NOT NULL, amount_base NUMERIC(14, 4) NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, comment TEXT DEFAULT NULL, external_reference VARCHAR(255) DEFAULT NULL, exchange_rate_to_base NUMERIC(18, 8) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
		$this->addSql('CREATE INDEX IDX_6D28840DFDA273EC ON payment (currency_code)');
		$this->addSql('CREATE INDEX IDX_6D28840DB092A811 ON payment (store_id)');
		$this->addSql('CREATE INDEX IDX_6D28840D8D9F6D38 ON payment (order_id)');
		$this->addSql('CREATE INDEX IDX_6D28840D558FBEB9 ON payment (purchase_id)');
		$this->addSql('CREATE INDEX IDX_6D28840DB03A8386 ON payment (created_by_id)');
		$this->addSql('CREATE INDEX IDX_6D28840D896DBBDE ON payment (updated_by_id)');
		$this->addSql('CREATE INDEX idx_payment_store_paid_at ON payment (store_id, paid_at)');
		$this->addSql('CREATE INDEX idx_payment_store_direction_paid_at ON payment (store_id, direction, paid_at)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DFDA273EC FOREIGN KEY (currency_code) REFERENCES currency (code) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DB092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D8D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D558FBEB9 FOREIGN KEY (purchase_id) REFERENCES purchase (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840DB03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT FK_6D28840D896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT chk_payment_amount_positive CHECK (amount > 0)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT chk_payment_amount_base_positive CHECK (amount_base > 0)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT chk_payment_exchange_rate_to_base_positive CHECK (exchange_rate_to_base > 0)');
		$this->addSql('ALTER TABLE payment ADD CONSTRAINT chk_payment_exactly_one_document CHECK (((order_id IS NOT NULL)::int + (purchase_id IS NOT NULL)::int) = 1)');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DFDA273EC');
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DB092A811');
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D8D9F6D38');
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D558FBEB9');
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840DB03A8386');
		$this->addSql('ALTER TABLE payment DROP CONSTRAINT FK_6D28840D896DBBDE');
		$this->addSql('DROP TABLE payment');
		$this->addSql('ALTER TABLE purchase DROP paid_at');
	}
}
