<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260509090838 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rate NUMERIC(18, 8) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_currency_code VARCHAR(3) NOT NULL, to_currency_code VARCHAR(3) NOT NULL, store_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9521FAB736D825A ON exchange_rate (from_currency_code)');
        $this->addSql('CREATE INDEX IDX_E9521FABD4AFB27A ON exchange_rate (to_currency_code)');
        $this->addSql('CREATE INDEX IDX_E9521FABB092A811 ON exchange_rate (store_id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FAB736D825A FOREIGN KEY (from_currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FABD4AFB27A FOREIGN KEY (to_currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT FK_E9521FABB092A811 FOREIGN KEY (store_id) REFERENCES store (id)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT chk_exchange_rate_rate_positive CHECK (rate > 0)');
        $this->addSql('ALTER TABLE exchange_rate ADD CONSTRAINT chk_exchange_rate_currencies_different CHECK (from_currency_code <> to_currency_code)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exchange_rate DROP CONSTRAINT FK_E9521FAB736D825A');
        $this->addSql('ALTER TABLE exchange_rate DROP CONSTRAINT FK_E9521FABD4AFB27A');
        $this->addSql('ALTER TABLE exchange_rate DROP CONSTRAINT FK_E9521FABB092A811');
        $this->addSql('DROP TABLE exchange_rate');
    }
}
