<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260510063402 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product_price (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, price NUMERIC(14, 4) NOT NULL, price_base NUMERIC(14, 4) NOT NULL, valid_from TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, valid_to TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, comment TEXT DEFAULT NULL, product_id INT NOT NULL, currency_code VARCHAR(3) NOT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6B9459854584665A ON product_price (product_id)');
        $this->addSql('CREATE INDEX IDX_6B945985FDA273EC ON product_price (currency_code)');
        $this->addSql('CREATE INDEX IDX_6B945985B092A811 ON product_price (store_id)');
        $this->addSql('CREATE INDEX IDX_6B945985B03A8386 ON product_price (created_by_id)');
        $this->addSql('CREATE INDEX IDX_6B945985896DBBDE ON product_price (updated_by_id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B9459854584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985FDA273EC FOREIGN KEY (currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT FK_6B945985896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT chk_product_price_price_positive CHECK (price > 0)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT chk_product_price_price_base_positive CHECK (price_base > 0)');
        $this->addSql('ALTER TABLE product_price ADD CONSTRAINT chk_product_price_valid_interval CHECK (valid_to IS NULL OR valid_to > valid_from)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B9459854584665A');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985FDA273EC');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985B092A811');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985B03A8386');
        $this->addSql('ALTER TABLE product_price DROP CONSTRAINT FK_6B945985896DBBDE');
        $this->addSql('DROP TABLE product_price');
    }
}
