<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260611100335 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Tax module phase 1: legal entities, tax rate sets, income records (+history), NBU exchange rates, tax reporting periods, accruals, report drafts; nullable store.legal_entity_id.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE income_record (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, recognized_at DATE NOT NULL, amount NUMERIC(14, 4) NOT NULL, amount_uah NUMERIC(14, 4) NOT NULL, nbu_exchange_rate NUMERIC(18, 8) NOT NULL, source_type VARCHAR(32) NOT NULL, source_id INT DEFAULT NULL, classification VARCHAR(32) NOT NULL, counterparty VARCHAR(255) DEFAULT NULL, payment_purpose TEXT DEFAULT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legal_entity_id INT NOT NULL, store_id INT DEFAULT NULL, currency_code VARCHAR(3) NOT NULL, payment_id INT DEFAULT NULL, refund_of_income_record_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64E7E9A66DEC420C ON income_record (legal_entity_id)');
        $this->addSql('CREATE INDEX IDX_64E7E9A6B092A811 ON income_record (store_id)');
        $this->addSql('CREATE INDEX IDX_64E7E9A6FDA273EC ON income_record (currency_code)');
        $this->addSql('CREATE INDEX IDX_64E7E9A64C3A3BB ON income_record (payment_id)');
        $this->addSql('CREATE INDEX IDX_64E7E9A61750589 ON income_record (refund_of_income_record_id)');
        $this->addSql('CREATE INDEX IDX_64E7E9A6B03A8386 ON income_record (created_by_id)');
        $this->addSql('CREATE INDEX IDX_64E7E9A6896DBBDE ON income_record (updated_by_id)');
        $this->addSql('CREATE INDEX idx_income_record_entity_recognized ON income_record (legal_entity_id, recognized_at)');
        $this->addSql('CREATE INDEX idx_income_record_entity_class_recognized ON income_record (legal_entity_id, classification, recognized_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_income_record_source ON income_record (source_type, source_id) WHERE (source_id IS NOT NULL)');
        $this->addSql('CREATE TABLE income_record_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, event_key VARCHAR(100) NOT NULL, payload JSON DEFAULT NULL, occurred_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_name_snapshot VARCHAR(255) DEFAULT NULL, income_record_id INT NOT NULL, actor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE1B664EA66DBF8 ON income_record_history (income_record_id)');
        $this->addSql('CREATE INDEX IDX_CE1B664E10DAF24A ON income_record_history (actor_id)');
        $this->addSql('CREATE INDEX idx_income_record_history_record_occurred_at ON income_record_history (income_record_id, occurred_at)');
        $this->addSql('CREATE TABLE legal_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, short_name VARCHAR(255) DEFAULT NULL, type VARCHAR(255) NOT NULL, tax_number VARCHAR(32) NOT NULL, tax_system VARCHAR(255) NOT NULL, ep_group INT DEFAULT NULL, ep_rate NUMERIC(5, 2) DEFAULT NULL, vat_payer BOOLEAN NOT NULL, esv_exempt BOOLEAN NOT NULL, registered_at DATE DEFAULT NULL, simplified_since DATE DEFAULT NULL, address TEXT DEFAULT NULL, kveds JSON DEFAULT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E21E9E13B03A8386 ON legal_entity (created_by_id)');
        $this->addSql('CREATE INDEX IDX_E21E9E13896DBBDE ON legal_entity (updated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_legal_entity_tax_number ON legal_entity (tax_number) WHERE (deleted_at IS NULL)');
        $this->addSql('CREATE TABLE nbu_exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, rate NUMERIC(18, 8) NOT NULL, source VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, currency_code VARCHAR(3) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7ADB4A4FDA273EC ON nbu_exchange_rate (currency_code)');
        $this->addSql('CREATE UNIQUE INDEX uniq_nbu_exchange_rate_currency_date ON nbu_exchange_rate (currency_code, date)');
        $this->addSql('CREATE TABLE tax_accrual (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tax_type VARCHAR(32) NOT NULL, accrued_amount NUMERIC(14, 4) NOT NULL, paid_amount NUMERIC(14, 4) NOT NULL, due_date DATE NOT NULL, paid_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(32) NOT NULL, bank_statement_row_id INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legal_entity_id INT NOT NULL, period_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AF9FD756DEC420C ON tax_accrual (legal_entity_id)');
        $this->addSql('CREATE INDEX IDX_AF9FD75EC8B7ADE ON tax_accrual (period_id)');
        $this->addSql('CREATE INDEX idx_tax_accrual_entity_due_date ON tax_accrual (legal_entity_id, due_date)');
        $this->addSql('CREATE INDEX idx_tax_accrual_status_due_date ON tax_accrual (status, due_date)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tax_accrual_entity_period_tax ON tax_accrual (legal_entity_id, period_id, tax_type)');
        $this->addSql('CREATE TABLE tax_rate_set (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, minimum_wage NUMERIC(14, 4) NOT NULL, subsistence_minimum NUMERIC(14, 4) NOT NULL, group1_income_limit NUMERIC(14, 4) NOT NULL, group2_income_limit NUMERIC(14, 4) NOT NULL, group3_income_limit NUMERIC(14, 4) NOT NULL, group1_ep_monthly NUMERIC(14, 4) NOT NULL, group2_ep_monthly NUMERIC(14, 4) NOT NULL, group3_ep_rate_pct NUMERIC(5, 2) NOT NULL, group3_ep_rate_vat_pct NUMERIC(5, 2) NOT NULL, esv_rate_pct NUMERIC(5, 2) NOT NULL, esv_monthly_min NUMERIC(14, 4) NOT NULL, vz_group12_monthly NUMERIC(14, 4) NOT NULL, vz_group3_rate_pct NUMERIC(5, 2) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_tax_rate_set_year ON tax_rate_set (year)');
        $this->addSql('CREATE TABLE tax_report_draft (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, report_type VARCHAR(64) NOT NULL, form_version VARCHAR(255) NOT NULL, payload JSON DEFAULT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(32) NOT NULL, legal_entity_id INT NOT NULL, period_id INT NOT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FC5032756DEC420C ON tax_report_draft (legal_entity_id)');
        $this->addSql('CREATE INDEX IDX_FC503275EC8B7ADE ON tax_report_draft (period_id)');
        $this->addSql('CREATE INDEX IDX_FC503275B03A8386 ON tax_report_draft (created_by_id)');
        $this->addSql('CREATE INDEX idx_tax_report_draft_entity_period ON tax_report_draft (legal_entity_id, period_id)');
        $this->addSql('CREATE TABLE tax_reporting_period (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, date_from DATE NOT NULL, date_to DATE NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, legal_entity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CEBBD1AB6DEC420C ON tax_reporting_period (legal_entity_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tax_reporting_period_entity_type_from ON tax_reporting_period (legal_entity_id, type, date_from)');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A66DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A6B092A811 FOREIGN KEY (store_id) REFERENCES store (id)');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A6FDA273EC FOREIGN KEY (currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A64C3A3BB FOREIGN KEY (payment_id) REFERENCES payment (id)');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A61750589 FOREIGN KEY (refund_of_income_record_id) REFERENCES income_record (id)');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A6B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE income_record ADD CONSTRAINT FK_64E7E9A6896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE income_record_history ADD CONSTRAINT FK_CE1B664EA66DBF8 FOREIGN KEY (income_record_id) REFERENCES income_record (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE income_record_history ADD CONSTRAINT FK_CE1B664E10DAF24A FOREIGN KEY (actor_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE legal_entity ADD CONSTRAINT FK_E21E9E13B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE legal_entity ADD CONSTRAINT FK_E21E9E13896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE nbu_exchange_rate ADD CONSTRAINT FK_E7ADB4A4FDA273EC FOREIGN KEY (currency_code) REFERENCES currency (code) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_accrual ADD CONSTRAINT FK_AF9FD756DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_accrual ADD CONSTRAINT FK_AF9FD75EC8B7ADE FOREIGN KEY (period_id) REFERENCES tax_reporting_period (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_report_draft ADD CONSTRAINT FK_FC5032756DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_report_draft ADD CONSTRAINT FK_FC503275EC8B7ADE FOREIGN KEY (period_id) REFERENCES tax_reporting_period (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tax_report_draft ADD CONSTRAINT FK_FC503275B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
        $this->addSql('ALTER TABLE tax_reporting_period ADD CONSTRAINT FK_CEBBD1AB6DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE store ADD legal_entity_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE store ADD CONSTRAINT FK_FF5758776DEC420C FOREIGN KEY (legal_entity_id) REFERENCES legal_entity (id)');
        $this->addSql('CREATE INDEX IDX_FF5758776DEC420C ON store (legal_entity_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE store DROP CONSTRAINT FK_FF5758776DEC420C');
        $this->addSql('DROP INDEX IDX_FF5758776DEC420C');
        $this->addSql('ALTER TABLE store DROP legal_entity_id');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A66DEC420C');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A6B092A811');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A6FDA273EC');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A64C3A3BB');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A61750589');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A6B03A8386');
        $this->addSql('ALTER TABLE income_record DROP CONSTRAINT FK_64E7E9A6896DBBDE');
        $this->addSql('ALTER TABLE income_record_history DROP CONSTRAINT FK_CE1B664EA66DBF8');
        $this->addSql('ALTER TABLE income_record_history DROP CONSTRAINT FK_CE1B664E10DAF24A');
        $this->addSql('ALTER TABLE legal_entity DROP CONSTRAINT FK_E21E9E13B03A8386');
        $this->addSql('ALTER TABLE legal_entity DROP CONSTRAINT FK_E21E9E13896DBBDE');
        $this->addSql('ALTER TABLE nbu_exchange_rate DROP CONSTRAINT FK_E7ADB4A4FDA273EC');
        $this->addSql('ALTER TABLE tax_accrual DROP CONSTRAINT FK_AF9FD756DEC420C');
        $this->addSql('ALTER TABLE tax_accrual DROP CONSTRAINT FK_AF9FD75EC8B7ADE');
        $this->addSql('ALTER TABLE tax_report_draft DROP CONSTRAINT FK_FC5032756DEC420C');
        $this->addSql('ALTER TABLE tax_report_draft DROP CONSTRAINT FK_FC503275EC8B7ADE');
        $this->addSql('ALTER TABLE tax_report_draft DROP CONSTRAINT FK_FC503275B03A8386');
        $this->addSql('ALTER TABLE tax_reporting_period DROP CONSTRAINT FK_CEBBD1AB6DEC420C');
        $this->addSql('DROP TABLE income_record');
        $this->addSql('DROP TABLE income_record_history');
        $this->addSql('DROP TABLE legal_entity');
        $this->addSql('DROP TABLE nbu_exchange_rate');
        $this->addSql('DROP TABLE tax_accrual');
        $this->addSql('DROP TABLE tax_rate_set');
        $this->addSql('DROP TABLE tax_report_draft');
        $this->addSql('DROP TABLE tax_reporting_period');
    }
}
