<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use App\Security\PermissionCatalog;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260526120000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add RBAC permissions, user groups, and per-user permission overrides.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(120) NOT NULL, name VARCHAR(120) NOT NULL, category VARCHAR(80) NOT NULL, description TEXT DEFAULT NULL, sort_order INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE UNIQUE INDEX uniq_permission_code ON permission (code)');
		$this->addSql('CREATE TABLE user_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, description TEXT DEFAULT NULL, system BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE UNIQUE INDEX uniq_user_group_code ON user_group (code)');
		$this->addSql('CREATE TABLE user_group_permission (user_group_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY(user_group_id, permission_id))');
		$this->addSql('CREATE INDEX IDX_F7BD1C3F1ED93D47 ON user_group_permission (user_group_id)');
		$this->addSql('CREATE INDEX IDX_F7BD1C3FFE54D947 ON user_group_permission (permission_id)');
		$this->addSql('CREATE TABLE user_user_group (user_id INT NOT NULL, user_group_id INT NOT NULL, PRIMARY KEY(user_id, user_group_id))');
		$this->addSql('CREATE INDEX IDX_3A45285A76ED395 ON user_user_group (user_id)');
		$this->addSql('CREATE INDEX IDX_3A45285A1ED93D47 ON user_user_group (user_group_id)');
		$this->addSql('CREATE TABLE user_permission_override (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, permission_id INT NOT NULL, effect VARCHAR(20) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE UNIQUE INDEX uniq_user_permission_override ON user_permission_override (user_id, permission_id)');
		$this->addSql('CREATE INDEX IDX_DACE79F0A76ED395 ON user_permission_override (user_id)');
		$this->addSql('CREATE INDEX IDX_DACE79F0FE54D947 ON user_permission_override (permission_id)');
		$this->addSql('ALTER TABLE user_group_permission ADD CONSTRAINT FK_F7BD1C3F1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE user_group_permission ADD CONSTRAINT FK_F7BD1C3FFE54D947 FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_3A45285A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE user_user_group ADD CONSTRAINT FK_3A45285A1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE user_permission_override ADD CONSTRAINT FK_DACE79F0A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE user_permission_override ADD CONSTRAINT FK_DACE79F0FE54D947 FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

		$this->seedPermissionsAndGroups();
		$this->mapLegacyRoles();
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE user_permission_override DROP CONSTRAINT FK_DACE79F0FE54D947');
		$this->addSql('ALTER TABLE user_permission_override DROP CONSTRAINT FK_DACE79F0A76ED395');
		$this->addSql('ALTER TABLE user_user_group DROP CONSTRAINT FK_3A45285A1ED93D47');
		$this->addSql('ALTER TABLE user_user_group DROP CONSTRAINT FK_3A45285A76ED395');
		$this->addSql('ALTER TABLE user_group_permission DROP CONSTRAINT FK_F7BD1C3FFE54D947');
		$this->addSql('ALTER TABLE user_group_permission DROP CONSTRAINT FK_F7BD1C3F1ED93D47');
		$this->addSql('DROP TABLE user_permission_override');
		$this->addSql('DROP TABLE user_user_group');
		$this->addSql('DROP TABLE user_group_permission');
		$this->addSql('DROP TABLE user_group');
		$this->addSql('DROP TABLE permission');
	}

	private function seedPermissionsAndGroups(): void
	{
		$catalog = new PermissionCatalog();
		$sortOrder = 10;

		foreach ($catalog->permissions() as $code => [$category, $name, $description]) {
			$this->addSql(
				'INSERT INTO permission (code, name, category, description, sort_order, created_at, updated_at) VALUES (?, ?, ?, ?, ?, NOW(), NOW())',
				[$code, $name, $category, $description, $sortOrder],
			);
			$sortOrder += 10;
		}

		foreach (PermissionCatalog::GROUPS as $code => [$name, $description, $system]) {
			$this->addSql(
				'INSERT INTO user_group (code, name, description, system, created_at, updated_at) VALUES (?, ?, ?, ?, NOW(), NOW())',
				[$code, $name, $description, $system],
			);

			foreach ($catalog->groupPermissions($code) as $permissionCode) {
				$this->addSql(
					'INSERT INTO user_group_permission (user_group_id, permission_id) SELECT user_group.id, permission.id FROM user_group, permission WHERE user_group.code = ? AND permission.code = ?',
					[$code, $permissionCode],
				);
			}
		}
	}

	private function mapLegacyRoles(): void
	{
		foreach ([
			'ROLE_SUPER_ADMIN' => 'super_admin',
			'ROLE_ADMIN' => 'admin',
			'ROLE_STORE_ADMIN' => 'store_admin',
			'ROLE_STORE_MANAGER' => 'manager',
			'ROLE_USER' => 'user',
		] as $role => $groupCode) {
			$this->addSql(
				'INSERT INTO user_user_group (user_id, user_group_id) SELECT users.id, user_group.id FROM users, user_group WHERE user_group.code = ? AND jsonb_exists(users.roles::jsonb, ?) ON CONFLICT DO NOTHING',
				[$groupCode, $role],
			);
		}
	}
}
