<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Add internal customer labels (per-store) and the customer <-> label many-to-many join table.
 */
final class Version20260602133427 extends AbstractMigration
{
	/**
	 * Seeded per store. Names are the English baseline; admins can rename per store (same approach as units).
	 * [code, name, color (bootstrap badge class), sort_order]
	 */
	private const array LABELS = [
		['aggressive', 'Aggressive', 'bg-danger', 10],
		['compliant', 'Compliant', 'bg-success', 20],
		['rational', 'Rational', 'bg-info text-dark', 30],
		['vip', 'VIP', 'bg-warning text-dark', 40],
		['problematic', 'Problematic', 'bg-danger', 50],
		['regular', 'Regular', 'bg-primary', 60],
		['bargainer', 'Bargainer', 'bg-secondary', 70],
		['needs_attention', 'Needs attention', 'bg-warning text-dark', 80],
		['frequent_returns', 'Frequently returns goods', 'bg-dark', 90],
	];

	public function getDescription(): string
	{
		return 'Add internal customer labels (per-store) and the customer <-> label many-to-many join table.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE customer_customer_label (customer_id INT NOT NULL, customer_label_id INT NOT NULL, PRIMARY KEY (customer_id, customer_label_id))');
		$this->addSql('CREATE INDEX IDX_59FF11199395C3F3 ON customer_customer_label (customer_id)');
		$this->addSql('CREATE INDEX IDX_59FF11191F7C6C16 ON customer_customer_label (customer_label_id)');
		$this->addSql('CREATE TABLE customer_label (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, name VARCHAR(255) NOT NULL, color VARCHAR(32) DEFAULT NULL, sort_order INT DEFAULT 0 NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_C09225D3B092A811 ON customer_label (store_id)');
		$this->addSql('CREATE INDEX IDX_C09225D3B03A8386 ON customer_label (created_by_id)');
		$this->addSql('CREATE INDEX IDX_C09225D3896DBBDE ON customer_label (updated_by_id)');
		$this->addSql('CREATE UNIQUE INDEX uniq_customer_label_store_code ON customer_label (store_id, code) WHERE (deleted_at IS NULL)');
		$this->addSql('ALTER TABLE customer_customer_label ADD CONSTRAINT FK_59FF11199395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE');
		$this->addSql('ALTER TABLE customer_customer_label ADD CONSTRAINT FK_59FF11191F7C6C16 FOREIGN KEY (customer_label_id) REFERENCES customer_label (id) ON DELETE CASCADE NOT DEFERRABLE');
		$this->addSql('ALTER TABLE customer_label ADD CONSTRAINT FK_C09225D3B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
		$this->addSql('ALTER TABLE customer_label ADD CONSTRAINT FK_C09225D3B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE customer_label ADD CONSTRAINT FK_C09225D3896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id)');

		// Seed the fixed internal label set for every existing store (idempotent).
		foreach (self::LABELS as [$code, $name, $color, $sortOrder]) {
			$this->addSql(
				'INSERT INTO customer_label (store_id, code, name, color, sort_order, status, created_at, updated_at) '
				. 'SELECT s.id, ?, ?, ?, ?, \'active\', NOW(), NOW() FROM store s '
				. 'WHERE NOT EXISTS (SELECT 1 FROM customer_label cl WHERE cl.store_id = s.id AND cl.code = ? AND cl.deleted_at IS NULL)',
				[$code, $name, $color, $sortOrder, $code],
			);
		}
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE customer_customer_label DROP CONSTRAINT FK_59FF11199395C3F3');
		$this->addSql('ALTER TABLE customer_customer_label DROP CONSTRAINT FK_59FF11191F7C6C16');
		$this->addSql('ALTER TABLE customer_label DROP CONSTRAINT FK_C09225D3B092A811');
		$this->addSql('ALTER TABLE customer_label DROP CONSTRAINT FK_C09225D3B03A8386');
		$this->addSql('ALTER TABLE customer_label DROP CONSTRAINT FK_C09225D3896DBBDE');
		$this->addSql('DROP TABLE customer_customer_label');
		$this->addSql('DROP TABLE customer_label');
	}
}
