<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260602120000 extends AbstractMigration
{
	private const array PERMISSIONS = [
		['order.discount.override', 'Orders', 'Override order discounts', 'Can enter manual discounts and allow below-cost discounted lines.'],
		['product_discount.view', 'Catalog', 'View product discounts', 'Can view product discount rules.'],
		['product_discount.manage', 'Catalog', 'Manage product discounts', 'Can create and edit product discount rules.'],
	];

	private const array GROUP_PERMISSION_CODES = [
		'admin' => ['order.discount.override', 'product_discount.view', 'product_discount.manage'],
		'store_admin' => ['order.discount.override', 'product_discount.view', 'product_discount.manage'],
	];

	public function getDescription(): string
	{
		return 'Add product discount rules and order discount snapshots.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE product_discount_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, store_id INT NOT NULL, created_by_id INT DEFAULT NULL, updated_by_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, percent NUMERIC(7, 4) NOT NULL, is_default BOOLEAN NOT NULL, status VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX idx_product_discount_rule_store_status ON product_discount_rule (store_id, status)');
		$this->addSql('CREATE INDEX IDX_2B7B584B092A811 ON product_discount_rule (store_id)');
		$this->addSql('CREATE INDEX IDX_2B7B584B03A8386 ON product_discount_rule (created_by_id)');
		$this->addSql('CREATE INDEX IDX_2B7B584896DBBDE ON product_discount_rule (updated_by_id)');
		$this->addSql('CREATE TABLE product_discount_target (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rule_id INT NOT NULL, product_id INT DEFAULT NULL, category_id INT DEFAULT NULL, target_type VARCHAR(32) NOT NULL, include_descendants BOOLEAN NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX idx_product_discount_target_rule ON product_discount_target (rule_id)');
		$this->addSql('CREATE INDEX idx_product_discount_target_product ON product_discount_target (product_id)');
		$this->addSql('CREATE INDEX idx_product_discount_target_category ON product_discount_target (category_id)');
		$this->addSql('ALTER TABLE product_discount_rule ADD CONSTRAINT FK_2B7B584B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE product_discount_rule ADD CONSTRAINT FK_2B7B584B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE product_discount_rule ADD CONSTRAINT FK_2B7B584896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE product_discount_rule ADD CONSTRAINT chk_product_discount_rule_percent CHECK (percent > 0 AND percent <= 100)');
		$this->addSql('ALTER TABLE product_discount_target ADD CONSTRAINT FK_1AA4065E744E0351 FOREIGN KEY (rule_id) REFERENCES product_discount_rule (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE product_discount_target ADD CONSTRAINT FK_1AA4065E4584665A FOREIGN KEY (product_id) REFERENCES product (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE product_discount_target ADD CONSTRAINT FK_1AA4065E12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql("ALTER TABLE product_discount_target ADD CONSTRAINT chk_product_discount_target_subject CHECK ((target_type = 'product' AND product_id IS NOT NULL AND category_id IS NULL) OR (target_type = 'category' AND category_id IS NOT NULL AND product_id IS NULL))");
		$this->addSql('ALTER TABLE order_entry ADD discount_rule_id INT DEFAULT NULL');
		$this->addSql('ALTER TABLE order_entry ADD discount_percent NUMERIC(7, 4) DEFAULT NULL');
		$this->addSql('ALTER TABLE order_entry ADD discount_mode VARCHAR(32) DEFAULT NULL');
		$this->addSql('ALTER TABLE order_entry ADD discount_rule_name_snapshot VARCHAR(255) DEFAULT NULL');
		$this->addSql('CREATE INDEX IDX_A8BFE98DC2466E40 ON order_entry (discount_rule_id)');
		$this->addSql('ALTER TABLE order_entry ADD CONSTRAINT FK_A8BFE98DC2466E40 FOREIGN KEY (discount_rule_id) REFERENCES product_discount_rule (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
		$this->addSql('ALTER TABLE order_entry ADD CONSTRAINT chk_order_entry_discount_percent CHECK (discount_percent IS NULL OR (discount_percent >= 0 AND discount_percent <= 100))');
		$this->addSql("UPDATE order_entry SET discount_percent = GREATEST(0, LEAST(100, ROUND((discount_amount / NULLIF(quantity * unit_price, 0)) * 100, 4))), discount_mode = 'manual_override' WHERE discount_amount IS NOT NULL AND discount_amount > 0 AND quantity > 0 AND unit_price > 0");
		$this->addSql("UPDATE order_entry SET discount_mode = 'none' WHERE discount_mode IS NULL");

		$this->seedPermissions();
	}

	public function down(Schema $schema): void
	{
		foreach (array_reverse(self::GROUP_PERMISSION_CODES) as $groupCode => $permissionCodes) {
			foreach ($permissionCodes as $permissionCode) {
				$this->addSql('DELETE FROM user_group_permission USING user_group, permission WHERE user_group_permission.user_group_id = user_group.id AND user_group_permission.permission_id = permission.id AND user_group.code = ? AND permission.code = ?', [$groupCode, $permissionCode]);
			}
		}

		foreach (array_reverse(self::PERMISSIONS) as [$code]) {
			$this->addSql('DELETE FROM permission WHERE code = ?', [$code]);
		}

		$this->addSql('ALTER TABLE order_entry DROP CONSTRAINT FK_A8BFE98DC2466E40');
		$this->addSql('ALTER TABLE order_entry DROP CONSTRAINT chk_order_entry_discount_percent');
		$this->addSql('DROP INDEX IDX_A8BFE98DC2466E40');
		$this->addSql('ALTER TABLE order_entry DROP discount_rule_id');
		$this->addSql('ALTER TABLE order_entry DROP discount_percent');
		$this->addSql('ALTER TABLE order_entry DROP discount_mode');
		$this->addSql('ALTER TABLE order_entry DROP discount_rule_name_snapshot');
		$this->addSql('ALTER TABLE product_discount_target DROP CONSTRAINT FK_1AA4065E744E0351');
		$this->addSql('ALTER TABLE product_discount_target DROP CONSTRAINT FK_1AA4065E4584665A');
		$this->addSql('ALTER TABLE product_discount_target DROP CONSTRAINT FK_1AA4065E12469DE2');
		$this->addSql('ALTER TABLE product_discount_target DROP CONSTRAINT chk_product_discount_target_subject');
		$this->addSql('ALTER TABLE product_discount_rule DROP CONSTRAINT FK_2B7B584B092A811');
		$this->addSql('ALTER TABLE product_discount_rule DROP CONSTRAINT FK_2B7B584B03A8386');
		$this->addSql('ALTER TABLE product_discount_rule DROP CONSTRAINT FK_2B7B584896DBBDE');
		$this->addSql('ALTER TABLE product_discount_rule DROP CONSTRAINT chk_product_discount_rule_percent');
		$this->addSql('DROP TABLE product_discount_target');
		$this->addSql('DROP TABLE product_discount_rule');
	}

	private function seedPermissions(): void
	{
		$sortOffset = 10;
		foreach (self::PERMISSIONS as [$code, $category, $name, $description]) {
			$this->addSql(
				'INSERT INTO permission (code, name, category, description, sort_order, created_at, updated_at) SELECT ?, ?, ?, ?, COALESCE(MAX(sort_order), 0) + ?, NOW(), NOW() FROM permission ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category, description = EXCLUDED.description, updated_at = NOW()',
				[$code, $name, $category, $description, $sortOffset],
			);
			$sortOffset += 10;
		}

		foreach (self::GROUP_PERMISSION_CODES as $groupCode => $permissionCodes) {
			foreach ($permissionCodes as $permissionCode) {
				$this->addSql(
					'INSERT INTO user_group_permission (user_group_id, permission_id) SELECT user_group.id, permission.id FROM user_group, permission WHERE user_group.code = ? AND permission.code = ? ON CONFLICT DO NOTHING',
					[$groupCode, $permissionCode],
				);
			}
		}
	}
}
