<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260602130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add comment type and importance flag to order comments, and per-user order comment read state.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE order_comment_read_state (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, last_read_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, order_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_825FCF398D9F6D38 ON order_comment_read_state (order_id)');
        $this->addSql('CREATE INDEX idx_order_comment_read_state_user ON order_comment_read_state (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_order_comment_read_state_order_user ON order_comment_read_state (order_id, user_id)');
        $this->addSql('ALTER TABLE order_comment_read_state ADD CONSTRAINT FK_825FCF398D9F6D38 FOREIGN KEY (order_id) REFERENCES orders (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE order_comment_read_state ADD CONSTRAINT FK_825FCF39A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) NOT DEFERRABLE');

        // Add with temporary defaults so existing rows backfill, then drop the default to match the mapping.
        $this->addSql("ALTER TABLE order_comment ADD type VARCHAR(32) DEFAULT 'general' NOT NULL");
        $this->addSql('ALTER TABLE order_comment ADD is_important BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE order_comment ALTER type DROP DEFAULT');
        $this->addSql('ALTER TABLE order_comment ALTER is_important DROP DEFAULT');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE order_comment_read_state DROP CONSTRAINT FK_825FCF398D9F6D38');
        $this->addSql('ALTER TABLE order_comment_read_state DROP CONSTRAINT FK_825FCF39A76ED395');
        $this->addSql('DROP TABLE order_comment_read_state');
        $this->addSql('ALTER TABLE order_comment DROP type');
        $this->addSql('ALTER TABLE order_comment DROP is_important');
    }
}
