<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260521120000 extends AbstractMigration
{
	public function getDescription(): string
	{
		return 'Add generic status history for purchase, inventory and production documents.';
	}

	public function up(Schema $schema): void
	{
		$this->addSql('CREATE TABLE status_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT NOT NULL, old_status VARCHAR(100) DEFAULT NULL, new_status VARCHAR(100) NOT NULL, comment TEXT DEFAULT NULL, changed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, changed_by_id INT DEFAULT NULL, store_id INT NOT NULL, PRIMARY KEY (id))');
		$this->addSql('CREATE INDEX IDX_6B6D4D3110DAF24A ON status_history (changed_by_id)');
		$this->addSql('CREATE INDEX IDX_6B6D4D31B092A811 ON status_history (store_id)');
		$this->addSql('CREATE INDEX idx_status_history_store_entity_changed_at ON status_history (store_id, entity_type, entity_id, changed_at)');
		$this->addSql('CREATE INDEX idx_status_history_store_changed_at ON status_history (store_id, changed_at)');
		$this->addSql('ALTER TABLE status_history ADD CONSTRAINT FK_6B6D4D3110DAF24A FOREIGN KEY (changed_by_id) REFERENCES users (id)');
		$this->addSql('ALTER TABLE status_history ADD CONSTRAINT FK_6B6D4D31B092A811 FOREIGN KEY (store_id) REFERENCES store (id) NOT DEFERRABLE');
	}

	public function down(Schema $schema): void
	{
		$this->addSql('ALTER TABLE status_history DROP CONSTRAINT FK_6B6D4D3110DAF24A');
		$this->addSql('ALTER TABLE status_history DROP CONSTRAINT FK_6B6D4D31B092A811');
		$this->addSql('DROP TABLE status_history');
	}
}
