#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path:
    en: /logout
    uk: /uk/logout
  methods: GET
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
  path:
    en: /
    uk: /uk
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
  defaults:
    route: admin_store_index
    permanent: true
