#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: /logout
  methods: GET
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"

homepage:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /admin/store
    permanent: true